function app = updateUI(app, column)
    app.GameBoard = app.GameBoard.updateGame(column);
    boardState = app.GameBoard.boardState;
    boardState = reshape(boardState.', 1, []);
    valueSet = ["IMG_0555.PNG", "IMG_0553.PNG","IMG_0554.PNG"];
    horizBoard = [valueSet(boardState + 1)];
    % horizBoard = arrayfun(@(x) M(x), boardState)
    
    % Thanks to Stephen on mathworks.com thread 16996
    [app.Image.ImageSource, app.Image_2.ImageSource, app.Image_3.ImageSource,... 
        app.Image_4.ImageSource, app.Image_5.ImageSource, app.Image_6.ImageSource,... 
        app.Image_7.ImageSource, app.Image_8.ImageSource, app.Image_9.ImageSource,... 
        app.Image_10.ImageSource, app.Image_11.ImageSource, app.Image_12.ImageSource,... 
        app.Image_13.ImageSource, app.Image_14.ImageSource, app.Image_15.ImageSource,... 
        app.Image_16.ImageSource, app.Image_17.ImageSource, app.Image_18.ImageSource,... 
        app.Image_19.ImageSource, app.Image_20.ImageSource, app.Image_21.ImageSource,... 
        app.Image_22.ImageSource, app.Image_23.ImageSource, app.Image_24.ImageSource,... 
        app.Image_25.ImageSource, app.Image_26.ImageSource, app.Image_27.ImageSource,... 
        app.Image_28.ImageSource, app.Image_29.ImageSource, app.Image_30.ImageSource,... 
        app.Image_31.ImageSource, app.Image_32.ImageSource, app.Image_33.ImageSource,... 
        app.Image_34.ImageSource, app.Image_35.ImageSource, app.Image_36.ImageSource,... 
        app.Image_37.ImageSource, app.Image_38.ImageSource, app.Image_39.ImageSource,... 
        app.Image_40.ImageSource, app.Image_41.ImageSource, app.Image_42.ImageSource] = subsref(horizBoard, substruct('{}',{':'}));

    if boardState.gameState ~= GameState.CONTINUE
        
    end
end